### ISSUE TITLE
I am looking for a means to change the folders at run time

### ISSUE THREAD

**Issue by MikeWilliams-UK** [Accenture/Ocaramba#403]
I want to be able to change the folder where files are downloaded, screen shots are saved at runtime

![image](https://user-images.githubusercontent.com/13162784/190182545-2ef0b40b-ad1d-4729-91c0-1006798eee66.png)

Is there any way to do this without editing the app settings file?

**Comment by pawelstryczek** [comment]
Hi Mike,

Unfortunately there is not possible in my opinion, no due to Ocaramba limitation but selenium. As far as I know we can change download folder using options before webdriver is started.

As workaround you can use similar solution like in link below:
https://stackoverflow.com/questions/45486121/change-download-location-and-name-for-each-file
